Ext.define('APP.store.call.storage',{
    extend:'APP.store.cross',
	alias:'store.call.storage',
	fields:[
		{name:'id',type:'int'},
		{name:'synctime',type:'date'},
		{name:'last_logintime',type:'date'},
		{name:'opendate',type:'date'},
		{name:'time',type:'date'},
		{name:'duration',type:'int'}
	],
	pageSize:false,
	sorters:[{property:'opendate',direction:'ASC'},{property:'id',direction:'ASC'}],
	proxy:{
		url:Boot.appUrl('/sd/call/getNo.do'),
		extraParams:{invalid:0,allot:0}
	}	
});
