Ext.define('APP.view.system.account.detail.info', {
  extend: 'Ext.Container',
  xtype: 'systemAccountDetailInfo',
  controller: 'system.account',
  padding: 5,
  scrollable: true,
  tpl: [
    '<div class="x-ui-part">',
			'<div class="x-ui-grid">',
				'<h3>账户信息</h3>',
				'<div class="x-ui-grid-inner">',
					'<dl><dt>账号</dt><dd><b>{account.login}</b></dd></dl>',
					'<dl><dt>类型</dt><dd>{account.type}</dd></dl>',
					'<dl><dt>杠杆</dt><dd>1:{account.leverage}</dd></dl>',
          '<dl>',
            '<dt>推广链接</dt>',
            '<dd>',
              '<a href="http://192.168.31.103:4003/#/account/index.html">http://192.168.31.103:4003/#/account/index.html</a>',
            '</dd>',
          '</dl>',
					'<dl>',
            '<dt>开户日期</dt>',
            '<dd>',
              '<span class="x-ui-text-green">北京：{account.regdate:date("Y-m-d H:i A")}</span><br/>',
              '<span class="x-ui-text-blue">伦敦：{account.regdate:utcDate("Y-m-d H:i A")}</span>',
					  '</dd>',
          '</dl>',
				'</div>',
			'</div>',
		'</div>',

		'<div class="x-ui-part">',
			'<div class="x-ui-grid">',
				'<h3>申请人档案</h3>',
				'<div class="x-ui-grid-inner">',
					'<dl><dt>姓名</dt><dd>{account.namecn} <s>{account.name}</s></dd></dl>',
					'<dl><dt>手机</dt><dd>{account.mobile}　<span class="x-ui-icon"><a href="tel:{mobile}" class="f-mt mt-mobile"></a></span></dd></dl>',
					'<dl><dt>Email</dt><dd>{account.email}　<span class="x-ui-icon"><a href="mailto:{email}" class="f-mt mt-email"></a></span></dd></dl>',
					'<dl><dt>证件</dt><dd>{account.identity_country} {account.identity_cardno}</dd></dl>',
				'</div>',
			'</div>',
		'</div>',

		'<div class="x-ui-part">',
			'<div class="x-ui-grid">',
				'<h3>账户资产</h3>',
				'<div class="x-ui-grid-inner">',
					'<dl><dt>余额</dt><dd><b class="x-ui-text-green">{account.balance:usMoney}</b></dd></dl>',
					'<dl><dt>信用</dt><dd><b class="x-ui-text-black">{account.credit:usMoney}</b></dd></dl>',
					'<dl><dt>净值</dt><dd><b class="x-ui-text-blue">{account.equity:usMoney}</b></dd></dl>',
					// '<dl><dt>已用</dt><dd><b class="x-ui-text-black">{mt4Data.margin:usMoney}</b></dd></dl>',
					// '<dl><dt>可用</dt><dd><b class="x-ui-text-red">{mt4Data.margin_free:usMoney}</b></dd></dl>',
					// '<tpl if="mt4Data.margin_level">',
					// 	'<dl><dt>可用比例</dt><dd>{mt4Data.margin_level:stringNumeral(2)} %</dd></dl>',
					// '</tpl>',
				'</div>',
			'</div>',
		'</div>'
  ],
  listeners:{
    // initialize:'onDetailInfoInitialize'
  }
});
